create table Employee (
ID NUMBER GENERATED by default on null as IDENTITY,
Name VARCHAR2(100),
Age INTEGER
)

insert into Employee(Name,Age) values ('Name1',11);
insert into Employee(Name,Age) values ('Name2',22);
insert into Employee(Name,Age) values ('Name3',33);
insert into Employee(Name,Age) values ('Name4',44);

SELECT *
FROM employee

DELETE Employee WHERE ID = 4


CREATE OR REPLACE PROCEDURE print_contact1( in_employee NUMBER)
IS
r_contact Employee%ROWTYPE;
BEGIN 
    SELECT *
    INTO r_contact
    FROM Employee 
    WHERE ID = in_employee
    
    dbms_output.put_line(r_contact.ID || ' ' r_contact.Name || ' ' r_contact.Age);
    
    EXCEPTION
        WHEN OTHERS THEN
         dbms_output.put_line( SQLERRM);
END

CREATE OR REPLACE PROCEDURE print_contact_user( in_user NUMBER)
IS
BEGIN 
    SELECT *
    FROM Employee 
    WHERE ID = in_user
    
    
END